[package]
edition = "2018"
name = "bench"
publish = false
version = "0.0.0"

[dependencies]
rand = "^0.8"
regex = "^1.4"
safe-regex = { version = "^0.2", path = "../safe-regex/" }

[dev-dependencies]
